### ISSUE TITLE
Incorrect parsing of images in CheckImage 

### ISSUE THREAD

**Issue by gloppasglop** [banzaicloud/anchore-image-validator#49]
**Incorrect parsing of images in CheckImage**

The parsing of an image tag is by the CheckImage function in ./pkg/anchore/client.go is incorrect when the port number is specified for a registry.

For exemple if the image name is: 

> myregistry.example.com:5000/myrepo/myimage:mytag

Then the parsed image name will be:

>myregistry.example.com

instead of:

>myregistry.example.com:5000/myrepo/myimage

and the parsed tag will be

>5000

instead of

>mytag

I am also suspecting that if the image name specifies the image digest, then the parsing will also be incorrect (but I have not tested it yet).

Exemple: 

> myregistry.example.com/myrepo/myimage@sha256:d004d...35a2

**Steps to reproduce the issue:**

Try to validate an image hosted on a registry running on a non-standard port or specified with a digest. 

**Expected behavior**

Maybe this could help doing the proper parsing: 

- https://github.com/docker/distribution/blob/master/reference/reference.go
- https://github.com/docker/distribution/blob/release/2.7/reference/normalize.go

**Comment by pbalogh-sa** [comment]
@gloppasglop Thanks for reporting this. We will dig into it.
